name: Python Application Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: |
        chmod +x
        bash exec.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pyflakes Syntax Checker
      uses: lgeiger/pyflakes-action@v1.0.1
      
      
